### ISSUE TITLE
API unavailable from localhost

### ISSUE THREAD

**Issue by MatsSchrader** [OpenReqEU/milla#2]
probably caused by CORS policy

**Comment by mzraatik** [comment]
Need more info, where deployed etc.

I suppose you cannot directly call https in ENG from http localhost. HTTP version is not working in ENG.

**Comment by MatsSchrader** [comment]
Sorry for being imprecise. When I called the milla API from my localhost I got an Error. But it looks like it resolved itself in the meantime.
