### ISSUE TITLE
Milla's endpoint GET /getTopProposedDependenciesOfRequirement has inconsistent results

### ISSUE THREAD

**Issue by RegenKordel** [OpenReqEU/milla#3]
For the issue QBS-585 the endpoint returns no results when specifying 5 maxResults and some results when specifying 20 maxResults.

**Comment by LloydThinks** [comment]
@laurtom Do you have any updates to this issue? Are you able to replicate this yourself?

**Comment by laurtom** [comment]
I fixed this quite a while ago.
